services:
  waterbase:
    build: .
    container_name: waterbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_PATH=/app/data
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - AUTH_HASH_KEY=${AUTH_HASH_KEY}
    volumes:
      - waterbase_data:/app/data

    # -------------------------------------------------------------------------
    # Limites de recursos do container
    # -------------------------------------------------------------------------
    # deploy:
    #  resources:
    #    limits:
    #      memory: 512M # Limite máximo de RAM
    #      cpus: "1" # Máximo de 1 núcleo de CPU
    #    reservations:
    #      memory: 256M # RAM garantida mínima
    #      cpus: "0.50" # CPU garantida mínima

volumes:
  waterbase_data:
